# action options:
# deploy_only       = deploy application to deploy_target only
# deploy_and_switch = deploy application to deploy_target and switch ALB traffic
# switch_only       = switch ALB traffic to deploy_target only
action=deploy_and_switch

# deploy_target options:
# blue
# green
deploy_target=green
