name: 🎓 Classroom Autograding

on:
  push:
    branches:
      - '**'

permissions:
  actions: read
  checks: write
  contents: read

jobs:
  grade:
    name: Run Classroom checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run autograding
        uses: classroom-resources/autograding@v1
